spring.application.name=Tis-back
# Datos de conexión (Asegúrate de haber creado la base de datos en MySQL primero)
spring.datasource.url=jdbc:mysql://localhost:3306/db_portafolios_tis?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=71718902

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081