spring.application.name=Tis-back

# Importar variables de entorno locales (solo para desarrollo)
spring.config.import=optional:file:env.properties

# Datos de conexión usando variables de entorno
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_portafolios_tis}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto dinámico para Railway
server.port=${PORT:8081}

# Configuración de servicios externos
brevo.api.key=${BREVO_KEY}
brevo.email.from=${BREVO_EMAIL}
url.front=${URL_FRONT}

# Si usas un JWT Secret, agrégalo aquí también
jwt.secret=${JWT_SECRET}